use std::path::PathBuf;

// Is this needed?
pub struct Attribute {
    pub id: usize,
    pub entity_id: usize,
    pub key: String,
    pub value: String,
}

pub struct Album {
    pub id: usize,
    pub artpath: PathBuf,
    pub added: f32,
    pub albumartist: String,
    pub albumartist_sort: String,
    pub albumartist_credit: String,
    pub album: String,
    pub genre: String,
    pub year: u16,
    pub month: u8,
    pub day: u8,
    pub disctotal: usize,
    pub comp: bool,
    pub mb_albumid: String,
    pub mb_albumartistid: String,
    pub mb_releasegroupid: String,
    pub albumtype: String,
    pub label: String,
    pub asin: String,
    pub catalognum: String,
    pub script: String,
    pub language: String,
    pub country: String,
    pub albumstatus: String,
    pub albumdisambig: String,
    pub rg_album_gain: f32,
    pub rg_album_peak: f32,
    pub r128_album_gain: usize,
    pub original_year: u16,
    pub original_month: u8,
    pub original_day: u8,
}

pub struct Item {
    pub id: usize,
    pub path: PathBuf,
    pub album_id: usize,
    pub title: String,
    pub artist: String,
    pub artist_sort: String,
    pub artist_credit: String,
    pub album: String,
    pub albumartist: String,
    pub albumartist_sort: String,
    pub albumartist_credit: String,
    pub genre: String,
    pub lyricist: String,
    pub composer: String,
    pub composer_sort: String,
    pub arranger: String,
    pub grouping: String,
    pub year: u16,
    pub month: usize,
    pub day: usize,
    pub track: usize,
    pub tracktotal: usize,
    pub disc: usize,
    pub disctotal: usize,
    pub lyrics: String,
    pub comments: String,
    pub bpm: usize,
    pub comp: bool,
    pub mb_trackid: String,
    pub mb_albumid: String,
    pub mb_artistid: String,
    pub mb_albumartistid: String,
    pub mb_releasetrackid: String,
    pub mb_releasegroupid: String,
    pub albumtype: String,
    pub label: String,
    pub acoustid_fingerprint: String,
    pub acoustid_id: String,
    pub asin: String,
    pub catalognum: String,
    pub script: String,
    pub language: String,
    pub country: String,
    pub albumstatus: String,
    pub media: String,
    pub albumdisambig: String,
    pub disctitle: String,
    pub encoder: String,
    pub rg_track_gain: f32,
    pub rg_track_peak: f32,
    pub rg_album_gain: f32,
    pub rg_album_peak: f32,
    pub r128_track_gain: usize,
    pub r128_album_gain: usize,
    pub original_year: u16,
    pub original_month: u8,
    pub original_day: u8,
    pub initial_key: String,
    pub length: f32,
    pub bitrate: usize,
    pub format: String,
    pub samplerate: u16,
    pub bitdepth: u16,
    pub channels: u8,
    pub mtime: f32,
    pub added: f32,
}
